spring:
  application:
    name: score-assistant
  ai:
    model:
      chat: openai
    openai:
      base-url: http://localhost:1234/v1
      api-key: ""
      timeout: 0s
      chat:
        options:
          model: google/gemma-4-26b-a4b-qat
  codec:
    max-in-memory-size: 25MB

  r2dbc:
    url: r2dbc:h2:mem:///scoreassistant;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password:

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

  graphql:
    websocket:
      path: /graphql
    graphiql:
      enabled: true
      path: /graphiql

  web:
    resources:
      static-locations: file:../frontend/dist/, classpath:/static/

server:
  port: 8080

logging:
  level:
    org.springframework.r2dbc: DEBUG
    com.scoreassistant: DEBUG
