// AUTO-GENERATED by Frontend Engineer workflow — DO NOT EDIT MANUALLY
import React, { useState, useEffect } from 'react';
import { shadcnComponents } from '@json-render/shadcn';
import { useStateStore } from '@json-render/react';
import type { ComponentType } from 'react';

// ────────────────────────────────────────────────────────────────────────────────
// Adapter: bridges @json-render/react's ComponentRenderProps  { element, children, emit, on, bindings, loading }
//          to   @json-render/shadcn's BaseComponentProps       { props, children, emit, on, bindings, loading }
// ────────────────────────────────────────────────────────────────────────────────
function adapt(Comp: ComponentType<any>): ComponentType<any> {
  const Adapted: ComponentType<any> = ({ element, children, emit, on, bindings, loading }: any) => {
    let store: any;
    try {
      store = useStateStore();
    } catch (e) {
      store = null;
    }

    const customEmit = (eventName: string, ...args: any[]) => {
      if (eventName === 'press' && store) {
        const label = element?.props?.label ?? '';
        const id = element?.props?.id ?? '';

        if (
          label.includes('建立') ||
          label.includes('新增') ||
          id.includes('create') ||
          id.includes('add')
        ) {
          const selected = store.get('/selected') || {};
          const updatedSelected = { ...selected };
          Object.keys(updatedSelected).forEach((k) => {
            updatedSelected[k] = null;
          });
          store.set('/selected', updatedSelected);
          store.set('/form', {});
        }

        if (
          label === '取消' || 
          id.includes('cancel') || 
          label === '儲存' || 
          label === '確認刪除' || 
          id.includes('submit') || 
          id.includes('confirm')
        ) {
          const modals = store.get('/modals') || {};
          const updated = { ...modals };
          Object.keys(updated).forEach((k) => {
            updated[k] = false;
          });
          store.set('/modals', updated);
        }
      }

      if (emit) {
        emit(eventName, ...args);
      }
    };

    const rawProps = element?.props ?? {};
    const props = { ...rawProps };

    if (element?.type === 'Button') {
      const v = props.variant;
      if (v === 'primary') {
        props.variant = 'default';
      } else if (v === 'danger') {
        props.variant = 'destructive';
      } else if (v === 'secondary') {
        props.variant = 'secondary';
      } else if (v === 'outline') {
        props.variant = 'outline';
      } else if (!v) {
        if (props.id?.includes('link') || props.id?.includes('crumb') || props.id?.includes('breadcrumb')) {
          props.variant = 'link';
        } else {
          props.variant = 'default';
        }
      }
      props['data-variant'] = props.variant;
    }

    return React.createElement(Comp, {
      props,
      children,
      emit: customEmit,
      on,
      bindings,
      loading,
    });
  };
  Adapted.displayName = `Adapted(${(Comp as any).displayName || Comp.name || 'Component'})`;
  return Adapted;
}

// ────────────────────────────────────────────────────────────────────────────────
// Custom composite components (ComponentRenderProps signature: { element, children, ... })
// ────────────────────────────────────────────────────────────────────────────────
const MetricCard: ComponentType<any> = ({ element }: any) => {
  const { label, value } = element?.props || {};
  return (
    <div className="bg-[#0f172a] border border-slate-800 p-6 rounded-xl shadow-lg relative overflow-hidden group hover:border-slate-700/80 transition-all duration-300">
      <div className="text-xs font-semibold tracking-wider text-slate-400 uppercase">{label}</div>
      <div className="mt-3 text-3xl font-extrabold text-white tracking-tight">{value ?? '—'}</div>
    </div>
  );
};

const DataTable: ComponentType<any> = ({ element, children, bindings }: any) => {
  let store: any;
  try {
    store = useStateStore();
  } catch (e) {
    store = null;
  }

  const { columns, data: rawData, label } = element?.props || {};
  
  // Resolve data:
  // 1. Try bindings (passed by json-render parser)
  // 2. Try resolving $bindState directly from the store
  // 3. Fallback to rawData
  let data = bindings?.data ?? rawData;
  if (typeof data === 'string' && data.startsWith('/') && store) {
    data = store.get(data);
  } else if (data && typeof data === 'object' && '$bindState' in data && store) {
    data = store.get(data.$bindState);
  }
  console.log('--- DEBUG DataTable: data =', data, 'store listSemesters =', store?.get('/data/listSemesters'));

  const rows: any[] = Array.isArray(data) ? data : [];
  return (
    <div className="bg-[#0d1321]/80 backdrop-blur-sm border border-slate-800/80 rounded-xl overflow-hidden shadow-xl">
      <table className="w-full text-left border-collapse text-slate-300 text-sm" aria-label={label}>
        <thead className="bg-slate-900/50 text-slate-400 font-medium border-b border-slate-800/80">
          <tr>
            {columns?.map((col: any) => (
              <th key={col.field} className="px-6 py-4">{col.label}</th>
            ))}
            {children && <th className="px-6 py-4 text-right">操作</th>}
          </tr>
        </thead>
        <tbody>
          {rows.length === 0 ? (
            <tr>
              <td
                colSpan={(columns?.length || 0) + (children ? 1 : 0)}
                className="px-6 py-8 text-center text-slate-500 font-medium"
              >
                (沒有資料)
              </td>
            </tr>
          ) : (
            rows.map((row: any, idx: number) => (
              <tr key={row.id || idx} className="border-b border-slate-800/40 hover:bg-slate-900/30 transition-colors">
                {columns?.map((col: any) => (
                  <td key={col.field} className="px-6 py-4">{String(row[col.field] ?? '')}</td>
                ))}
                {children && (
                  <td className="px-6 py-4 text-right space-x-2">
                    {React.Children.map(children, (child) => {
                      if (!React.isValidElement(child)) return child;
                      return (
                        <div
                          className="inline-block"
                          onClickCapture={() => {
                            if (store && row?.id) {
                              const tableId = element?.props?.id || '';
                              const dataRef = element?.props?.dataRef || '';
                              let entity = '';
                              if (dataRef && dataRef.startsWith('list')) {
                                const raw = dataRef.slice(4);
                                const base = raw.endsWith('es') ? raw.slice(0, -2) : raw.endsWith('s') ? raw.slice(0, -1) : raw;
                                entity = base.charAt(0).toLowerCase() + base.slice(1);
                              } else if (tableId) {
                                entity = tableId.replace('-table', '').replace('-list', '');
                              }
                              if (entity) {
                                store.set(`/selected/${entity}Id`, row.id);
                              }
                            }
                          }}
                        >
                          {child}
                        </div>
                      );
                    })}
                  </td>
                )}
              </tr>
            ))
          )}
        </tbody>
      </table>
    </div>
  );
};

const MultiSelect: ComponentType<any> = () => (
  <div className="border border-slate-800 p-2 rounded bg-slate-950 text-slate-400">MultiSelect</div>
);

const Breadcrumb: ComponentType<any> = ({ children }: any) => (
  <nav className="flex text-sm font-medium text-slate-400 py-2" aria-label="Breadcrumb">
    <ol className="inline-flex items-center space-x-1 md:space-x-3">
      {children}
    </ol>
  </nav>
);

const AlertDialog: ComponentType<any> = ({ element, children }) => {
  const { label, text } = element?.props || {};
  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm">
      <div className="bg-[#0f172a] border border-slate-800 p-6 rounded-xl shadow-2xl max-w-md w-full mx-4">
        <h3 className="text-lg font-bold text-white mb-2">{label || text || '確認操作'}</h3>
        <div className="text-sm text-slate-400 mb-6">{children}</div>
      </div>
    </div>
  );
};

const ChartPlaceholder = (type: string): ComponentType<any> =>
  ({ element }: any) => (
    <div className="border border-slate-800 p-4 rounded bg-slate-950 text-slate-400">
      {type} Chart: {element?.props?.label}
    </div>
  );

// ────────────────────────────────────────────────────────────────────────────────
// DatePicker — native HTML date picker, writes to explicit storePath
// Schema props: id, label, name, storePath (e.g. "/form/start-date"), disabled
// ────────────────────────────────────────────────────────────────────────────────
const DatePicker = ({ element }: any) => {
  let store: any;
  try { store = useStateStore(); } catch { store = null; }

  const { id, label, name, storePath, disabled } = element?.props || {};

  // Local state mirrors the store — provides immediate controlled re-render
  const [localValue, setLocalValue] = useState<string>(() =>
    (storePath && store ? (store.get(storePath) as string) : '') ?? ''
  );

  const storeVal = (storePath && store ? (store.get(storePath) as string) : '') ?? '';
  useEffect(() => {
    setLocalValue(storeVal);
  }, [storeVal]);

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const val = e.target.value; // always YYYY-MM-DD from native date picker
    setLocalValue(val);
    if (storePath && store) store.set(storePath, val);
  };

  return (
    <div className="grid gap-1.5">
      {label && (
        <label htmlFor={id} className="text-sm font-medium leading-none text-foreground">
          {label}
        </label>
      )}
      <input
        type="date"
        id={id}
        name={name || id}
        value={localValue}
        onChange={handleChange}
        disabled={!!disabled}
        className={
          'flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 ' +
          'text-sm text-foreground ring-offset-background cursor-pointer ' +
          'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring ' +
          'disabled:cursor-not-allowed disabled:opacity-50 [color-scheme:dark]'
        }
      />
    </div>
  );
};

// ────────────────────────────────────────────────────────────────────────────────
// Component Registry
// ────────────────────────────────────────────────────────────────────────────────
export const componentRegistry: Record<string, ComponentType<any>> = {
  // ── 1. All 36 @json-render/shadcn presets, adapted to ComponentRenderProps ──
  ...Object.fromEntries(
    Object.entries(shadcnComponents).map(([key, Comp]) => [key, adapt(Comp as ComponentType<any>)])
  ),

  // ── 2. Custom layout shell ──────────────────────────────────────────────────
  'Container:page': ({ children }) => (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6 space-y-6">{children}</div>
  ),

  // ── 3. Custom composite components ─────────────────────────────────────────
  'MetricCard': MetricCard,
  'DataTable': DataTable,
  'MultiSelect': MultiSelect,
  'Breadcrumb': Breadcrumb,
  'AlertDialog': AlertDialog,
  'DatePicker': DatePicker,

  // ── 4. Chart wrappers ───────────────────────────────────────────────────────
  'Chart:bar': ChartPlaceholder('Bar'),
  'Chart:line': ChartPlaceholder('Line'),
  'Chart:pie': ChartPlaceholder('Pie'),

  // ── 5. Native HTML wrapper (no-op passthrough) ──────────────────────────────
  'div': ({ element, children }) => (
    <div className={element?.props?.className}>{children}</div>
  ),
};
