// AUTO-GENERATED by Frontend Engineer workflow
// Source: docs/02-design-specs/uml/students_contract.puml (resolver: listStudents)
// DO NOT EDIT MANUALLY — expand query fields from interface contract return type

import { useQuery } from '@tanstack/react-query';
import { gql, request } from 'graphql-request';
import { GRAPHQL_ENDPOINT } from '@/lib/graphql-client';

export interface Students {
  [key: string]: unknown;
}

const LISTSTUDENTS_QUERY = gql`
  query listStudents($filter: StudentFilterInput) {
    listStudents(filter: $filter) {
      id
      classId
      studentNumber
      studentName
    }
  }
`;

export const listStudentsKeys = {
  all: ['listStudents'] as const,
  filtered: (filter: Record<string, unknown>) => ['listStudents', filter] as const,
};

export function useListStudents(filter?: Record<string, unknown>) {
  return useQuery({
    queryKey: filter ? listStudentsKeys.filtered(filter) : listStudentsKeys.all,
    queryFn: () =>
      request<{ listStudents: Students[] }>(
        GRAPHQL_ENDPOINT,
        LISTSTUDENTS_QUERY,
        { filter }
      ).then(data => data.listStudents),
  });
}
