// AUTO-GENERATED by Frontend Engineer workflow
// Source: docs/02-design-specs/uml/semesters_contract.puml (resolver: listSemesters)
// DO NOT EDIT MANUALLY — expand query fields from interface contract return type

import { useQuery } from '@tanstack/react-query';
import { gql, request } from 'graphql-request';
import { GRAPHQL_ENDPOINT } from '@/lib/graphql-client';

export interface Semesters {
  [key: string]: unknown;
}

const LISTSEMESTERS_QUERY = gql`
  query listSemesters($filter: SemestersFilterInput) {
    listSemesters(filter: $filter) {
      id
    }
  }
`;

export const listSemestersKeys = {
  all: ['listSemesters'] as const,
  filtered: (filter: Record<string, unknown>) => ['listSemesters', filter] as const,
};

export function useListSemesters(filter?: Record<string, unknown>) {
  return useQuery({
    queryKey: filter ? listSemestersKeys.filtered(filter) : listSemestersKeys.all,
    queryFn: () =>
      request<{ listSemesters: Semesters[] }>(
        GRAPHQL_ENDPOINT,
        LISTSEMESTERS_QUERY,
        { filter }
      ).then(data => data.listSemesters),
  });
}
