// AUTO-GENERATED by Frontend Engineer workflow
// Source: docs/02-design-specs/api-contracts/openapi.yaml (operationId: getClassById)
// DO NOT EDIT MANUALLY

import { useQuery } from '@tanstack/react-query';
import { api } from '@/lib/api-client';

export interface ClassResponse {
  [key: string]: unknown;
}

export const getClassByIdKeys = {
  all: ['getClassById'] as const,
  detail: (id: string) => ['getClassById', id] as const,
};

export function useGetClassById(id: string) {
  return useQuery({
    queryKey: getClassByIdKeys.detail(id),
    queryFn: () => api.get<ClassResponse>(`/classes/${id}`),
  });
}
