// AUTO-GENERATED by Frontend Engineer workflow
// Source: docs/02-design-specs/uml/classes_contract.puml (resolver: listClasses)
// DO NOT EDIT MANUALLY — expand query fields from interface contract return type

import { useQuery } from '@tanstack/react-query';
import { gql, request } from 'graphql-request';
import { GRAPHQL_ENDPOINT } from '@/lib/graphql-client';

export interface Classes {
  [key: string]: unknown;
}

const LISTCLASSES_QUERY = gql`
  query listClasses($filter: ClassFilterInput) {
    listClasses(filter: $filter) {
      id
      semesterId
      className
    }
  }
`;

export const listClassesKeys = {
  all: ['listClasses'] as const,
  filtered: (filter: Record<string, unknown>) => ['listClasses', filter] as const,
};

export function useListClasses(filter?: Record<string, unknown>) {
  return useQuery({
    queryKey: filter ? listClassesKeys.filtered(filter) : listClassesKeys.all,
    queryFn: () =>
      request<{ listClasses: Classes[] }>(
        GRAPHQL_ENDPOINT,
        LISTCLASSES_QUERY,
        { filter }
      ).then(data => data.listClasses),
  });
}
