// AUTO-GENERATED by Frontend Engineer workflow
// Source: docs/02-design-specs/uml/gradeitems_contract.puml (resolver: listGradeItems)
// DO NOT EDIT MANUALLY — expand query fields from interface contract return type

import { useQuery } from '@tanstack/react-query';
import { gql, request } from 'graphql-request';
import { GRAPHQL_ENDPOINT } from '@/lib/graphql-client';

export interface GradeItems {
  [key: string]: unknown;
}

const LISTGRADEITEMS_QUERY = gql`
  query listGradeItems($filter: GradeItemsFilterInput) {
    listGradeItems(filter: $filter) {
      id
    }
  }
`;

export const listGradeItemsKeys = {
  all: ['listGradeItems'] as const,
  filtered: (filter: Record<string, unknown>) => ['listGradeItems', filter] as const,
};

export function useListGradeItems(filter?: Record<string, unknown>) {
  return useQuery({
    queryKey: filter ? listGradeItemsKeys.filtered(filter) : listGradeItemsKeys.all,
    queryFn: () =>
      request<{ listGradeItems: GradeItems[] }>(
        GRAPHQL_ENDPOINT,
        LISTGRADEITEMS_QUERY,
        { filter }
      ).then(data => data.listGradeItems),
  });
}
