// AUTO-GENERATED by Frontend Engineer workflow
// Source: docs/02-design-specs/uml/graderecords_contract.puml (resolver: listGradeRecords)
// DO NOT EDIT MANUALLY — expand query fields from interface contract return type

import { useQuery } from '@tanstack/react-query';
import { gql, request } from 'graphql-request';
import { GRAPHQL_ENDPOINT } from '@/lib/graphql-client';

export interface GradeRecords {
  [key: string]: unknown;
}

const LISTGRADERECORDS_QUERY = gql`
  query listGradeRecords($filter: GradeRecordsFilterInput) {
    listGradeRecords(filter: $filter) {
      id
    }
  }
`;

export const listGradeRecordsKeys = {
  all: ['listGradeRecords'] as const,
  filtered: (filter: Record<string, unknown>) => ['listGradeRecords', filter] as const,
};

export function useListGradeRecords(filter?: Record<string, unknown>) {
  return useQuery({
    queryKey: filter ? listGradeRecordsKeys.filtered(filter) : listGradeRecordsKeys.all,
    queryFn: () =>
      request<{ listGradeRecords: GradeRecords[] }>(
        GRAPHQL_ENDPOINT,
        LISTGRADERECORDS_QUERY,
        { filter }
      ).then(data => data.listGradeRecords),
  });
}
