// AUTO-GENERATED by Frontend Engineer workflow
// Source: docs/02-design-specs/uml/attachments_contract.puml (resolver: listAttachments)
// DO NOT EDIT MANUALLY — expand query fields from interface contract return type

import { useQuery } from '@tanstack/react-query';
import { gql, request } from 'graphql-request';
import { GRAPHQL_ENDPOINT } from '@/lib/graphql-client';

export interface Attachments {
  [key: string]: unknown;
}

const LISTATTACHMENTS_QUERY = gql`
  query listAttachments($filter: AttachmentFilterInput) {
    listAttachments(filter: $filter) {
      id
      gradeRecordId
      fileName
      mimeType
      fileSize
      uploadedAt
    }
  }
`;

export const listAttachmentsKeys = {
  all: ['listAttachments'] as const,
  filtered: (filter: Record<string, unknown>) => ['listAttachments', filter] as const,
};

export function useListAttachments(filter?: Record<string, unknown>) {
  return useQuery({
    queryKey: filter ? listAttachmentsKeys.filtered(filter) : listAttachmentsKeys.all,
    queryFn: () =>
      request<{ listAttachments: Attachments[] }>(
        GRAPHQL_ENDPOINT,
        LISTATTACHMENTS_QUERY,
        { filter }
      ).then(data => data.listAttachments),
  });
}
