// AUTO-GENERATED by Frontend Engineer workflow
// Source: docs/02-design-specs/api-contracts/openapi.yaml (operationId: getSemesterById)
// DO NOT EDIT MANUALLY

import { useQuery } from '@tanstack/react-query';
import { api } from '@/lib/api-client';

export interface SemesterResponse {
  [key: string]: unknown;
}

export const getSemesterByIdKeys = {
  all: ['getSemesterById'] as const,
  detail: (id: string) => ['getSemesterById', id] as const,
};

export function useGetSemesterById(id: string) {
  return useQuery({
    queryKey: getSemesterByIdKeys.detail(id),
    queryFn: () => api.get<SemesterResponse>(`/semesters/${id}`),
  });
}
