// AUTO-GENERATED by Frontend Engineer workflow — DO NOT EDIT MANUALLY
import { useEffect } from 'react';
import { Renderer, useStateStore } from '@json-render/react';
import { componentRegistry } from '@/json-render/component-registry';
import { useListSemesters } from '@/hooks/use-list-semesters';
import spec from '@/schemas/semester-list.render-schema.json';

export default function SemesterListPage() {
  const store = useStateStore();
  const { data } = useListSemesters();

  useEffect(() => {
    if (data) {
      const mapped = data.map((s: any) => ({
        id: s.id,
        name: s.semesterName,
        startDate: s.startDate,
        endDate: s.endDate,
        classCount: 0,
      }));
      const current = store.get('/data/listSemesters');
      if (JSON.stringify(current) !== JSON.stringify(mapped)) {
        store.set('/data/listSemesters', mapped);
      }
    }
  }, [data, store]);

  return <Renderer spec={spec as any} registry={componentRegistry} />;
}
