// AUTO-GENERATED by Frontend Engineer workflow — DO NOT EDIT MANUALLY
import { Renderer } from '@json-render/react';
import { componentRegistry } from '@/json-render/component-registry';
import spec from '@/schemas/semester-list.render-schema.json';

export default function SemesterListPage() {
  return <Renderer spec={spec as any} registry={componentRegistry} />;
}
